Repository Typerproject/Frontend, pull requests merged in 2024-06, with the labels that each got.

#1 Navbar 생성, 폰트 적용
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Layout.tsx
  frontend/src/components/Navbar/Navbar.tsx
  frontend/src/index.css
  frontend/src/main-router.tsx
  frontend/src/routes/main/MainPage.tsx
Labels: ✨ feat, 🎨 design

#5 feat: 마이페이지 헤더, 프로필, 팔로우 UI 기본 구성
  frontend/src/main-router.tsx
  frontend/src/routes/my/MyPage.tsx
  frontend/src/routes/my/component/FollowList.jsx
Labels: ✨ feat

#8 feat: 마이페이지 게시글 미리보기
  frontend/src/components/Post/Post.tsx
  frontend/src/main-router.tsx
  frontend/src/routes/my/MyPage.tsx
  frontend/src/routes/postDetail/component/PostContent.tsx
Labels: ✨ feat

#9 ✨feat: editor 뉴스 커스텀 블록 구현
  frontend/src/api/editorAPI.ts
  frontend/src/components/Navbar/Navbar.tsx
  frontend/src/routes/editor/component/Editor.tsx
  frontend/src/routes/editor/component/blockTools/chart/Chart.tsx
  frontend/src/routes/editor/component/blockTools/chart/ChartBlock.tsx
  frontend/src/routes/editor/component/blockTools/news/News.tsx
  frontend/src/routes/editor/component/blockTools/news/NewsBlock.tsx
  frontend/src/routes/postDetail/component/Comment.tsx
  frontend/src/routes/postDetail/component/InputComment.tsx
  frontend/src/routes/postDetail/component/PostContent.tsx
  frontend/src/routes/postDetail/component/ViewEditor.tsx
  frontend/src/routes/postDetail/component/WriterInfo.tsx
Labels: ✨ feat

#10 feat: 팔로워/팔로잉 삭제 기능
  frontend/package-lock.json
  frontend/src/components/Post/Post.tsx
  frontend/src/main-router.tsx
  frontend/src/routes/my/MyPage.tsx
  frontend/src/routes/my/component/FollowList.jsx
  frontend/src/routes/my/component/FollowList.tsx
Labels: ✨ feat

#15 feat: redux-persist 적용
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/login/Redirect.tsx
  frontend/src/store/index.ts
  frontend/src/store/reducers/user.ts
Labels: ✨ feat

#19 feat: 팔로우 리스트 드롭바 추가 및 팔로우 유저 클릭 시 페이지 이동
  frontend/src/routes/my/MyPage.tsx
  frontend/src/routes/my/component/FollowList.tsx
Labels: ✨ feat

#20 desing: 마이페이지 edit 클릭 시 input 박스 디자인 수정
  frontend/src/routes/my/MyPage.tsx
Labels: 🎨 design

#28 feat: 마이페이지 게시글 미리보기 유저 정보로 설정
  frontend/src/components/Post/Post.tsx
  frontend/src/routes/my/MyPage.tsx
Labels: ✨ feat

#37 feat: 게시물 미리보기
  frontend/src/api/userAPI.ts
  frontend/src/components/Post/Post.tsx
  frontend/src/routes/my/MyPage.tsx
Labels: ✨ feat, 🎨 design

#44 design: 마이페이지 반응형 및 한글 폰트 변경
  frontend/src/components/Post/Post.tsx
  frontend/src/index.css
  frontend/src/routes/my/MyPage.tsx
  frontend/tailwind.config.js
Labels: 🎨 design

#48 feat: 메인 페이지 반응형 적용
  frontend/src/api/userAPI.ts
  frontend/src/components/Post/Post.tsx
  frontend/src/routes/main/component/Post.tsx
  frontend/src/routes/my/MyPage.tsx
  frontend/src/routes/my/component/Modal.tsx
  frontend/tailwind.config.js
Labels: ✨ feat, 🎨 design

#52 feat: footer 추가했습니다
  frontend/src/components/Footbar/Footbar.tsx
  frontend/src/components/Layout.tsx
  frontend/src/routes/main/MainPage.tsx
  frontend/src/routes/main/component/Post.tsx
  frontend/src/routes/my/MyPage.tsx
  frontend/src/routes/scrap/ScrapPage.tsx
Labels: ✨ feat, 🎨 design

#58 design: 폰일 경우 메인 페이지 반응형 추가
  frontend/src/components/Post/Post.tsx
  frontend/src/routes/main/MainPage.tsx
  frontend/src/routes/main/component/Post.tsx
  frontend/src/routes/my/MyPage.tsx
  frontend/tailwind.config.js
Labels: 🎨 design

#59 design: 마이 페이지 폰에서 반응형 적용
  frontend/src/api/userAPI.ts
  frontend/src/components/Footbar/Footbar.tsx
  frontend/src/components/Post/Post.tsx
  frontend/src/routes/main/MainPage.tsx
  frontend/src/routes/my/MyPage.tsx
Labels: 🎨 design

#71 feat: 팔로우 리스트 높이 변동 및 마이페이지 페이지네이션 적용
  frontend/src/api/postDetailAPI.ts
  frontend/src/api/userAPI.ts
  frontend/src/components/Post/Post.tsx
  frontend/src/routes/main/component/Post.tsx
  frontend/src/routes/my/MyPage.tsx
  frontend/src/routes/my/component/FollowList.tsx
  frontend/src/routes/my/component/Modal.tsx
Labels: ✨ feat, 🎨 design

#74 feat: 네브바 드롭다운, 차트블록 날짜 태그 수정, css 및 텍스트 수정
  frontend/src/api/postDetailAPI.ts
  frontend/src/components/Navbar/Navbar.tsx
  frontend/src/main-router.tsx
  frontend/src/routes/editor/component/blockTools/chart/ChartBlock.tsx
  frontend/src/routes/main/MainPage.tsx
  frontend/src/routes/main/component/Post.tsx
  frontend/src/routes/main/component/PostLoading.tsx
  frontend/src/routes/main/component/SliderTest.tsx
Labels: ✨ feat, 🎨 design

#79 design: 검색 페이지 반응형 수정
  frontend/src/components/search/Search.tsx
  frontend/src/routes/main/component/Post.tsx
  frontend/src/routes/my/MyPage.tsx
Labels: 🎨 design
